apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: besu-standalone-besu-node-data
  labels:
    app.kubernetes.io/name: standalone-besu
    app.kubernetes.io/component: storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
