apiVersion: v1
kind: ConfigMap
metadata:
  name: besu-standalone-besu-node-auth
  labels:
    app.kubernetes.io/name: standalone-besu
    app.kubernetes.io/component: auth
data:
  credentials.txt: |
    [users]
    paladin = "0x2a26f7d04905d69e8b26b8e6df60fcc6c9c425c0d2acd0f2e7f0b8c8b8c8b8c8"
    permissions_paladin = ["*:*"]


  #   credentials.txt: |
  # # Besu RPC Authentication Credentials
  # # Format: [users] section with username = "hashed_password"
  # # and permissions_username = ["api_group:method", ...]
  # [users]
  # paladin = "0x2a26f7d04905d69e8b26b8e6df60fcc6c9c425c0d2acd0f2e7f0b8c8b8c8b8c8"
  # permissions_paladin = ["*:*"]