contracts:
  factory:
    abiAndBytecode:
      path: ./helpers/abis/ZetoFactory.json
  # the Zeto factory is a CloneFactory, which needs implementation
  # contracts to be set
  implementations:
    - name: Groth16Verifier_Anon
      abiAndBytecode:
        path: ./helpers/abis/Groth16Verifier_Anon.json
    - name: Groth16Verifier_AnonBatch
      abiAndBytecode:
        path: ./helpers/abis/Groth16Verifier_AnonBatch.json
    - name: Groth16Verifier_Deposit
      abiAndBytecode:
        path: ./helpers/abis/Groth16Verifier_Deposit.json
    - name: Groth16Verifier_Withdraw
      abiAndBytecode:
        path: ./helpers/abis/Groth16Verifier_Withdraw.json
    - name: Groth16Verifier_WithdrawBatch
      abiAndBytecode:
        path: ./helpers/abis/Groth16Verifier_WithdrawBatch.json
    - name: Groth16Verifier_Burn
      abiAndBytecode:
        path: ./helpers/abis/Groth16Verifier_Burn.json
    - name: Groth16Verifier_BurnBatch
      abiAndBytecode:
        path: ./helpers/abis/Groth16Verifier_BurnBatch.json
    - name: Zeto_Anon
      verifier: Groth16Verifier_Anon
      batchVerifier: Groth16Verifier_AnonBatch
      depositVerifier: Groth16Verifier_Deposit
      withdrawVerifier: Groth16Verifier_Withdraw
      batchWithdrawVerifier: Groth16Verifier_WithdrawBatch
      lockVerifier: Groth16Verifier_Anon
      batchLockVerifier: Groth16Verifier_AnonBatch
      burnVerifier: Groth16Verifier_Burn
      batchBurnVerifier: Groth16Verifier_BurnBatch
      circuits:
        deposit:
          name: deposit
        withdraw:
          name: withdraw
        transfer:
          name: anon
        transferLocked:
          name: anon
      cloneable: true
      abiAndBytecode:
        path: ./helpers/abis/Zeto_Anon.json
