db:
  type: sqlite
  sqlite:
    uri: ':memory:'
    autoMigrate: true
    migrationsDir: './db/migrations/sqlite'
rpcServer:
  http:
    port: 0
  ws:
    disabled: true
blockchain:
  ws:
    url: ws://localhost:8546
