# Installation mode: determines the default resources to deploy when installing this chart.
# Available options:
# - devnet (default): Deploys a complete Paladin network (default: 3 nodes), including Domains and Smart Contract CRs.
# - basenet: Deploys only Smart Contract CRs without Domains or Paladin nodes.
# - none / operator-only (or leave empty): Deploys only the Paladin operator without additional resources.
mode: devnet

# Number of Paladin to deploy. Relevant only when mode is set to "devnet".
nodeCount: 3

# Number of besu nodes to deploy. When not set, defaults to 1.
besuNodeCount: 3

# Default values for paladin-operator
operator:
  name: paladin-operator
  namespace: "" # DEPRECATED: Use the namespace field in the HelmRelease instead. e.g. helm install ... --namespace <namespace>
  image:
    repository: ghcr.io/lf-decentralized-trust-labs/paladin-operator
    tag: latest
    pullPolicy: Always

  serviceAccount:
    create: true
    automount: true
    annotations: {}

  podSecurityContext:
    runAsNonRoot: true

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]

  livenessProbe:
    httpGet:
      path: /healthz
      port: 8081
      scheme: HTTP
  readinessProbe:
    httpGet:
      path: /readyz
      port: 8081
      scheme: HTTP

  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi

  env:
    - name: CONFIG_PATH
      value: /etc/config

  # Volumes configuration
  volumes:
  - name: config
    configMap:
      name: paladin-operator     

  volumeMounts:
  - name: config
    mountPath: /etc/config/config.json    # Where the file will be mounted in the container
    subPath: config.json                  # The key (file) from the ConfigMap to mount
                     
  labels:
    control-plane: controller-manager

  annotations: {}

  nodeSelector: {}
  tolerations: []
  affinity: {}

  service:
    type: ClusterIP
    port: 80

  configMap:
    # Referring to the external config.yaml file
    dataFile: assets/config.json
# Prometheus dependencies
prometheus:
  enabled: false
  prometheus:
    namespace: prometheus 
  alertmanager:
    enabled: false 
  server:
    enabled: false
  pushgateway:
    enabled: false  # Enable if you need the push gateway

postgres: # the postgres container runs as a sidecar to the paladin container
  image:
    repository: postgres
    tag: 17.6
    pullPolicy: IfNotPresent

# Smart Contracts References
# Only used when mode is "attach" to join an existing network.
# - Set 'address' to join an existing deployment from another operator.
smartContractsReferences:
  notoFactory:
    address: ""
  zetoFactory:
    address: ""
  penteFactory:
    address: ""
  registry:
    address: ""

# Smart Contract Deployments Configuration
# Controls the signing keys for smart contract deployments.
# If a 'from' key is set for a specific contract, that value is used.
# If not set, it falls back to the value in 'default'.
# If default not set, it falls back to the value set by the operator
smartContractDeployments:
  default:
    from: ""
  registry:
    from: ""
  noto_factory:
    from: ""
  pente_factory:
    from: ""
  zeto_g16_anon:
    from: ""
  zeto_g16_anon_batch:
    from: ""
  zeto_g16_anon_enc:
    from: ""
  zeto_g16_anon_enc_batch:
    from: ""
  zeto_g16_anon_nullifier_transfer:
    from: ""
  zeto_g16_anon_nullifier_transfer_batch:
    from: ""
  zeto_g16_anon_nullifier_kyc_transfer:
    from: ""
  zeto_g16_anon_nullifier_kyc_transfer_batch:
    from: ""
  zeto_g16_anon_nullifier_kyc_transfer_locked:
    from: ""
  zeto_g16_anon_nullifier_kyc_transfer_locked_batch:
    from: ""
  zeto_g16_deposit:
    from: ""
  zeto_g16_withdraw:
    from: ""
  zeto_g16_withdraw_batch:
    from: ""
  zeto_g16_withdraw_nullifier:
    from: ""
  zeto_g16_withdraw_nullifier_batch:
    from: ""
  zeto_poseidon_unit2l:
    from: ""
  zeto_poseidon_unit3l:
    from: ""
  zeto_smt_lib:
    from: ""
  zeto_impl_anon:
    from: ""
  zeto_impl_anon_enc:
    from: ""
  zeto_impl_anon_nullifier:
    from: ""
  zeto_impl_anon_nullifier_kyc:
    from: ""
  zeto_factory:
    from: ""

# Transaction Invoke Configuration
# Controls the signing keys for transaction invocations.
# If a 'from' key is set for a specific transaction, that value is used.
# If not set, it falls back to the value in 'default'.
# If default not set, it falls back to the value set by the operator
transactionInvokes:
  default:
    from: ""
  zeto_anon:
    from: ""
  zeto_anon_enc:
    from: ""
  zeto_anon_nullifier:
    from: ""
  zeto_anon_nullifier_kyc:
    from: ""

    
# Install CRDs as part of the chart installation
# When this is set to false, the CRDs are expected to be installed separately
installCRDs: false

# Setting for devnet mode 
paladin:
  nodeNamePrefix: node
  image:
    repository: ghcr.io/lf-decentralized-trust-labs/paladin
    tag: main
    pullPolicy: Always
  labels:
    app: paladin
  baseNodePort: 31548

# Setting for devnet mode 
besu:
  nodeNamePrefix: node
  image:
    repository: hyperledger/besu
    tag: 25.8.0
    pullPolicy: IfNotPresent
  labels:
    app: besu
  baseNodePort: 31545

# Domains can be configured with a default signing identity
domains:
  noto:
    fixedSigningIdentity: ""
  pente:
    fixedSigningIdentity: ""
  zeto:
    fixedSigningIdentity: ""