name: 'Update YAML File'
description: 'Update values in a YAML file'
inputs:
  file:
    description: 'The path to the YAML file to update'
    required: true
  expressions:
    description: 'A multi-line string of yq update expressions to apply.'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install yq
      shell: bash
      run: |
        # This check prevents re-downloading yq on every call within the same job
        if ! command -v yq &> /dev/null
        then
            echo "yq not found, installing..."
            wget https://github.com/mikefarah/yq/releases/download/v4.34.1/yq_linux_amd64 -O yq
            chmod +x yq
            sudo mv yq /usr/local/bin/
        else
            echo "yq is already installed."
        fi

    - name: Update YAML file
      shell: bash
      run: |
        set -e
        echo "Applying expressions to ${{ inputs.file }}"
        
        # Create a temporary file to hold the expressions
        echo "${{ inputs.expressions }}" > expressions.txt
        
        # Create a temporary copy of the target file to apply changes to
        temp_file="${{ inputs.file }}.tmp"
        cp "${{ inputs.file }}" "$temp_file"

        # Read the file line by line and apply each expression to the temp file
        while IFS= read -r expression; do
          # Skip empty lines
          if [[ -n "$expression" ]]; then
            echo "Applying: yq e -i '$expression' $temp_file"
            yq e -i "$expression" "$temp_file"
          fi
        done < expressions.txt

        # Replace the original file with the updated one
        mv "$temp_file" "${{ inputs.file }}"

        echo "Updated content of ${{ inputs.file }}:"
        cat "${{ inputs.file }}"