# permissions for end users to view paladindomains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator-go
    app.kubernetes.io/managed-by: kustomize
  name: paladindomain-viewer-role
rules:
- apiGroups:
  - core.paladin.io
  resources:
  - paladindomains
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.paladin.io
  resources:
  - paladindomains/status
  verbs:
  - get
