---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - core.paladin.io
  resources:
  - besugeneses
  - besus
  - paladindomains
  - paladinregistrations
  - paladinregistries
  - paladins
  - smartcontractdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.paladin.io
  resources:
  - besugeneses/finalizers
  - besus/finalizers
  - paladindomains/finalizers
  - paladinregistrations/finalizers
  - paladinregistries/finalizers
  - paladins/finalizers
  - smartcontractdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - core.paladin.io
  resources:
  - besugeneses/status
  - besus/status
  - paladindomains/status
  - paladinregistrations/status
  - paladinregistries/status
  - paladins/status
  - smartcontractdeployments/status
  verbs:
  - get
  - patch
  - update
