---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - core.paladin.io
  resources:
  - transactioninvokes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.paladin.io
  resources:
  - transactioninvokes/finalizers
  verbs:
  - update
- apiGroups:
  - core.paladin.io
  resources:
  - transactioninvokes/status
  verbs:
  - get
  - patch
  - update
