services:
    postgres:
        container_name: paladin-test-db
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: my-secret
    besu:
        container_name: paladin-test-besu
        image: hyperledger/besu:latest
        ports:
            - 8545:8545
            - 8546:8546
        command:
            - --rpc-http-enabled
            - --rpc-ws-enabled
