services:
    postgres:
        container_name: paladin-test-db
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: my-secret
    besu:
        container_name: paladin-test-besu
        image: hyperledger/besu:latest
        volumes:
        - ./test/besu:/var/besu:rw
        ports:
            - 8545:8545
            - 8546:8546
        command:
            - --rpc-http-enabled
            - --rpc-http-api=ETH,QBFT,WEB3,DEBUG
            - --rpc-ws-enabled
            - --rpc-ws-api=ETH,QBFT,WEB3,DEBUG
            - --tx-pool=SEQUENCED
            - --tx-pool-limit-by-account-percentage=1.0
            - --tx-pool-max-size=1000000
            - --target-gas-limit=30000000
            - --genesis-file=/var/besu/genesis.json
            - --data-path=/var/besu/data
            - --node-private-key-file=/var/besu/key
