apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.operator.name }}
  {{- with .Values.operator.configMap.annotations }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.operator.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config.json: |
{{ tpl (.Files.Get .Values.operator.configMap.dataFile) . | indent 4 }}

