apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.operator.name }}
  namespace: {{ .Values.operator.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.operator.name }}     
    namespace: {{ .Values.operator.namespace }}             
roleRef:
  kind: Role
  name: {{ .Values.operator.name }}
  apiGroup: rbac.authorization.k8s.io
