apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.operator.name }}
  namespace: {{ .Values.operator.namespace }}
  {{- with .Values.operator.service.annotations }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.operator.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  type: {{ .Values.operator.service.type }}
  ports:
    - port: {{ .Values.operator.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.operator.name }}
    
