template: testify
pkgname: "{{.SrcPackageName}}mocks"
structname: "{{.InterfaceName}}"
filename: "{{.SrcPackageName}}mocks.go"
dir: "mocks/{{.SrcPackageName}}mocks"
packages:
  github.com/LF-Decentralized-Trust-labs/paladin/core/internal/sequencer/common:
    config:
      all: true
      dir: "{{.InterfaceDir}}"
      pkgname: "{{.SrcPackageName}}"
      structname: "Mock{{.InterfaceName}}"
  github.com/LF-Decentralized-Trust-labs/paladin/core/internal/sequencer/metrics:
    config:
      all: true
      dir: "{{.InterfaceDir}}"
      pkgname: "{{.SrcPackageName}}"
      structname: "Mock{{.InterfaceName}}"
  github.com/LF-Decentralized-Trust-labs/paladin/core/internal/sequencer/syncpoints:
    config:
      all: true
      dir: "{{.InterfaceDir}}"
      pkgname: "{{.SrcPackageName}}"
      structname: "Mock{{.InterfaceName}}"
  github.com/LF-Decentralized-Trust-labs/paladin/core/internal/sequencer/coordinator/transaction:
    config:
      all: true
      dir: "{{.InterfaceDir}}"
      pkgname: "{{.SrcPackageName}}"
      structname: "Mock{{.InterfaceName}}"
  github.com/LF-Decentralized-Trust-labs/paladin/core/internal/sequencer/sender:
    config:
      all: true
      dir: "{{.InterfaceDir}}"
      pkgname: "{{.SrcPackageName}}"
      structname: "Mock{{.InterfaceName}}"
  github.com/LF-Decentralized-Trust-labs/paladin/core/internal/sequencer/coordinator:
    config:
      all: true
      dir: "{{.InterfaceDir}}"
      pkgname: "{{.SrcPackageName}}"
      structname: "Mock{{.InterfaceName}}"
  github.com/LF-Decentralized-Trust-labs/paladin/core/internal/sequencer/transport:
    config:
      all: true
      dir: "{{.InterfaceDir}}"
      pkgname: "{{.SrcPackageName}}"
      structname: "Mock{{.InterfaceName}}"
  github.com/LF-Decentralized-Trust-labs/paladin/core/internal/sequencer:
    config:
      all: true
      dir: "{{.InterfaceDir}}"
      pkgname: "{{.SrcPackageName}}"
      structname: "Mock{{.InterfaceName}}"
