name: Override SDK tag
description: 'Override the SDK tag in the examples'
inputs:
  sdk_version:
    description: 'The version of the SDK to install'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Override SDK tag
      shell: bash
      run: |
        echo "sdk_version: ${{ inputs.sdk_version }}"
        # remove the v prefix from the tag if its there
        sdk_version=$(echo "${{ inputs.sdk_version }}" | sed 's/^v//')
        for example in examples/*/; do
          if [ -d "$example" ]; then
            echo "Overriding $example"
            cd "$example"
            # override only if the package.json has 'paladin-sdk' as a dependency
            if grep -q "paladin-sdk" package.json; then
              # First, remove the existing file: dependency
              npm uninstall @lfdecentralizedtrust-labs/paladin-sdk
              # Then, install the new version
              npm install @lfdecentralizedtrust-labs/paladin-sdk@$sdk_version
            fi
            cd ../..
          fi
        done