// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sequencer

import (
	"github.com/LF-Decentralized-Trust-labs/paladin/core/internal/sequencer/coordinator"
	"github.com/LF-Decentralized-Trust-labs/paladin/core/internal/sequencer/sender"
	"github.com/LF-Decentralized-Trust-labs/paladin/core/internal/sequencer/transport"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDistributedSequencer creates a new instance of MockDistributedSequencer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDistributedSequencer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDistributedSequencer {
	mock := &MockDistributedSequencer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDistributedSequencer is an autogenerated mock type for the DistributedSequencer type
type MockDistributedSequencer struct {
	mock.Mock
}

type MockDistributedSequencer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDistributedSequencer) EXPECT() *MockDistributedSequencer_Expecter {
	return &MockDistributedSequencer_Expecter{mock: &_m.Mock}
}

// GetCoordinator provides a mock function for the type MockDistributedSequencer
func (_mock *MockDistributedSequencer) GetCoordinator() coordinator.SeqCoordinator {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCoordinator")
	}

	var r0 coordinator.SeqCoordinator
	if returnFunc, ok := ret.Get(0).(func() coordinator.SeqCoordinator); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(coordinator.SeqCoordinator)
		}
	}
	return r0
}

// MockDistributedSequencer_GetCoordinator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCoordinator'
type MockDistributedSequencer_GetCoordinator_Call struct {
	*mock.Call
}

// GetCoordinator is a helper method to define mock.On call
func (_e *MockDistributedSequencer_Expecter) GetCoordinator() *MockDistributedSequencer_GetCoordinator_Call {
	return &MockDistributedSequencer_GetCoordinator_Call{Call: _e.mock.On("GetCoordinator")}
}

func (_c *MockDistributedSequencer_GetCoordinator_Call) Run(run func()) *MockDistributedSequencer_GetCoordinator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDistributedSequencer_GetCoordinator_Call) Return(seqCoordinator coordinator.SeqCoordinator) *MockDistributedSequencer_GetCoordinator_Call {
	_c.Call.Return(seqCoordinator)
	return _c
}

func (_c *MockDistributedSequencer_GetCoordinator_Call) RunAndReturn(run func() coordinator.SeqCoordinator) *MockDistributedSequencer_GetCoordinator_Call {
	_c.Call.Return(run)
	return _c
}

// GetSender provides a mock function for the type MockDistributedSequencer
func (_mock *MockDistributedSequencer) GetSender() sender.SeqSender {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSender")
	}

	var r0 sender.SeqSender
	if returnFunc, ok := ret.Get(0).(func() sender.SeqSender); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sender.SeqSender)
		}
	}
	return r0
}

// MockDistributedSequencer_GetSender_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSender'
type MockDistributedSequencer_GetSender_Call struct {
	*mock.Call
}

// GetSender is a helper method to define mock.On call
func (_e *MockDistributedSequencer_Expecter) GetSender() *MockDistributedSequencer_GetSender_Call {
	return &MockDistributedSequencer_GetSender_Call{Call: _e.mock.On("GetSender")}
}

func (_c *MockDistributedSequencer_GetSender_Call) Run(run func()) *MockDistributedSequencer_GetSender_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDistributedSequencer_GetSender_Call) Return(seqSender sender.SeqSender) *MockDistributedSequencer_GetSender_Call {
	_c.Call.Return(seqSender)
	return _c
}

func (_c *MockDistributedSequencer_GetSender_Call) RunAndReturn(run func() sender.SeqSender) *MockDistributedSequencer_GetSender_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransportWriter provides a mock function for the type MockDistributedSequencer
func (_mock *MockDistributedSequencer) GetTransportWriter() transport.TransportWriter {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTransportWriter")
	}

	var r0 transport.TransportWriter
	if returnFunc, ok := ret.Get(0).(func() transport.TransportWriter); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(transport.TransportWriter)
		}
	}
	return r0
}

// MockDistributedSequencer_GetTransportWriter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransportWriter'
type MockDistributedSequencer_GetTransportWriter_Call struct {
	*mock.Call
}

// GetTransportWriter is a helper method to define mock.On call
func (_e *MockDistributedSequencer_Expecter) GetTransportWriter() *MockDistributedSequencer_GetTransportWriter_Call {
	return &MockDistributedSequencer_GetTransportWriter_Call{Call: _e.mock.On("GetTransportWriter")}
}

func (_c *MockDistributedSequencer_GetTransportWriter_Call) Run(run func()) *MockDistributedSequencer_GetTransportWriter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDistributedSequencer_GetTransportWriter_Call) Return(transportWriter transport.TransportWriter) *MockDistributedSequencer_GetTransportWriter_Call {
	_c.Call.Return(transportWriter)
	return _c
}

func (_c *MockDistributedSequencer_GetTransportWriter_Call) RunAndReturn(run func() transport.TransportWriter) *MockDistributedSequencer_GetTransportWriter_Call {
	_c.Call.Return(run)
	return _c
}
