apiVersion: core.paladin.io/v1alpha1
kind: PaladinDomain
metadata:
  labels:
    app.kubernetes.io/name: operator-go
    app.kubernetes.io/managed-by: kustomize
    paladin.io/domain-name: zeto
  name: zeto
spec:
  smartContractDeployment: zeto-factory
  plugin:
    type: c-shared
    library: /app/domains/libzeto.so
  configJSON: |
    {}
