apiVersion: core.paladin.io/v1alpha1
kind: Paladin
metadata:
  name: node2
spec:
  config: |
    log:
      level: debug
  database:
    mode: sidecarPostgres
    migrationMode: auto
  baseLedgerEndpoint:
    type: local
    local:
      nodeName: node2
  secretBackedSigners:
    - name: signer-1
      secret: node2.keys
      type: autoHDWallet
      keySelector: .*
  domains:
    - labelSelector:
        matchLabels:
          paladin.io/domain-name: noto
    - labelSelector:
        matchLabels:
          paladin.io/domain-name: zeto          
    - labelSelector:
        matchLabels:
          paladin.io/domain-name: pente
  registries:
    - labelSelector:
        matchLabels:
          paladin.io/registry-name: evm-registry
  transports:
    - name: grpc
      plugin:
        type: c-shared
        library: /app/transports/libgrpc.so
      configJSON: |
        {
          "port": 9000,
          "address": "0.0.0.0"
        }
      ports:
      - name: transport-grpc
        port: 9000
        targetPort: 9000
      tls:
        secretName: paladin-node2-mtls
        certName: paladin-node2-mtls
  service:
    type: NodePort
    ports:
    - name: rpc-http
      port: 8548
      nodePort: 31648 # see paladin-kind.yaml
    - name: rpc-ws
      port: 8549
      nodePort: 31649 # see paladin-kind.yaml
