apiVersion: core.paladin.io/v1alpha1
kind: PaladinDomain
metadata:
  labels:
    app.kubernetes.io/name: operator-go
    app.kubernetes.io/managed-by: kustomize
    paladin.io/domain-name: zeto
  name: zeto
spec:
  smartContractDeployment: zeto-factory
  allowSigning: true
  plugin:
    type: c-shared
    library: /app/domains/libzeto.so
  configJSON: |
    {
      "domainContracts": {
        "Implementations": [
          {
            "CircuitId": "anon",
            "Name": "Zeto_Anon"
          },
          {
            "CircuitId": "anon_enc",
            "Name": "Zeto_AnonEnc"
          },
          {
            "CircuitId": "anon_nullifier",
            "Name": "Zeto_AnonNullifier"
          }
        ]
      },
      "snarkProver": {
        "circuitsDir": "/app/domains/zeto/zkp",
        "provingKeysDir": "/app/domains/zeto/zkp"
      }
    }
