## Append samples of your project ##
resources:
  - cert_issuer_selfsigned.yaml
  - core_v1alpha1_paladin_node1.yaml
  - core_v1alpha1_paladin_node2.yaml
  - core_v1alpha1_paladin_node3.yaml
  - core_v1alpha1_besu_node1.yaml
  - core_v1alpha1_besu_node2.yaml
  - core_v1alpha1_besu_node3.yaml
  - core_v1alpha1_besugenesis.yaml
  - core_v1alpha1_paladinregistry.yaml
  - core_v1alpha1_paladindomain_noto.yaml
  - core_v1alpha1_paladindomain_pente.yaml
  - core_v1alpha1_paladindomain_zeto.yaml
  - core_v1alpha1_paladinregistration_node1_admin.yaml
  - core_v1alpha1_paladinregistration_node2.yaml
  - core_v1alpha1_paladinregistration_node3.yaml
  - core_v1alpha1_transactioninvoke_zeto_register_anon.yaml
  - core_v1alpha1_transactioninvoke_zeto_register_anon_enc.yaml
  - core_v1alpha1_transactioninvoke_zeto_register_anon_nullifier.yaml
  - core_v1alpha1_transactioninvoke_zeto_register_anon_nullifier_kyc.yaml
  # Smart contracts - note these CRs are generate dynamically by the build
  - core_v1alpha1_smartcontractdeployment_registry.yaml
  - core_v1alpha1_smartcontractdeployment_noto_factory.yaml
  - core_v1alpha1_smartcontractdeployment_pente_factory.yaml
  - core_v1alpha1_smartcontractdeployment_zeto_factory.yaml
  - core_v1alpha1_smartcontractdeployment_zeto_g16_deposit.yaml
  - core_v1alpha1_smartcontractdeployment_zeto_g16_withdraw.yaml
  - core_v1alpha1_smartcontractdeployment_zeto_g16_withdraw_batch.yaml
  - core_v1alpha1_smartcontractdeployment_zeto_g16_withdraw_nullifier.yaml
  - core_v1alpha1_smartcontractdeployment_zeto_g16_withdraw_nullifier_batch.yaml
  - core_v1alpha1_smartcontractdeployment_zeto_g16_anon.yaml
  - core_v1alpha1_smartcontractdeployment_zeto_g16_anon_batch.yaml
  - core_v1alpha1_smartcontractdeployment_zeto_g16_anon_enc.yaml
  - core_v1alpha1_smartcontractdeployment_zeto_g16_anon_enc_batch.yaml
  - core_v1alpha1_smartcontractdeployment_zeto_g16_anon_nullifier_transfer.yaml
  - core_v1alpha1_smartcontractdeployment_zeto_g16_anon_nullifier_transfer_batch.yaml
  - core_v1alpha1_smartcontractdeployment_zeto_g16_anon_nullifier_kyc_transfer.yaml
  - core_v1alpha1_smartcontractdeployment_zeto_g16_anon_nullifier_kyc_transfer_batch.yaml
  - core_v1alpha1_smartcontractdeployment_zeto_g16_anon_nullifier_kyc_transfer_locked.yaml
  - core_v1alpha1_smartcontractdeployment_zeto_g16_anon_nullifier_kyc_transfer_locked_batch.yaml
  - core_v1alpha1_smartcontractdeployment_zeto_impl_anon.yaml
  - core_v1alpha1_smartcontractdeployment_zeto_impl_anon_enc.yaml
  - core_v1alpha1_smartcontractdeployment_zeto_impl_anon_nullifier.yaml
  - core_v1alpha1_smartcontractdeployment_zeto_impl_anon_nullifier_kyc.yaml
  - core_v1alpha1_smartcontractdeployment_zeto_poseidon_unit2l.yaml
  - core_v1alpha1_smartcontractdeployment_zeto_poseidon_unit3l.yaml
  - core_v1alpha1_smartcontractdeployment_zeto_smt_lib.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
