db:
  type: sqlite
  sqlite:
    uri: ':memory:'
    autoMigrate: true
    migrationsDir: './db/migrations/sqlite'
rpcServer:
  http:
    address: 0.0.0.0
    port: 49610
  ws:
    disabled: true
blockchain:
  ws:
    url: ws://besu:8546
    initialConnectAttempts: 25
bus:
  grpc:
    socketProtocol: tcp
    socketAddress: ":49611"
signer:
  keyDerivation:
    type: "bip32"
  keyStore:
    type: "static"
    snarkProver:
      circuitsDir: zkp
      provingKeysDir: zkp
    static:
      keys:
        seed:
          encoding: none
          # DO NOT USE THIS MNEMONIC FOR ANYTHING APART FROM TESTBED TESTING
          inline: lift steak taste love canvas crush oil fortune pave joy empty hedgehog radio outdoor twice
