db:
  type: sqlite
  sqlite:
    uri: ':memory:'
    autoMigrate: true
    migrationsDir: './db/migrations/sqlite'
    debugQueries: true
rpcServer:
  http:
    port: 49603
  ws:
    disabled: true
blockchain:
  ws:
    url: ws://localhost:8546
    initialConnectAttempts: 25
bus:
  grpc:
    socketAddress: /tmp/testbed.paladin.1542386773.sock
signer:
  keyDerivation:
    type: "bip32"
  keyStore:
    type: "static"
    static:
      keys:
        seed:
          encoding: none
          # DO NOT USE THIS MNEMONIC FOR ANYTHING APART FROM TESTBED TESTING
          inline: lift steak taste love canvas crush oil fortune pave joy empty hedgehog radio outdoor twice
    