contracts:
  factory:
    # if the address is set, it takes precendece over
    # the rest of the properties for deploying a factory
    address: '0x0'
  # the Zeto factory is a CloneFactory, which needs implementation
  # contracts to be set
  implementations:
    - name: Zeto_Anon
      circuitId: anon
      address:
      abi:
    - name: Zeto_AnonEnc
      circuitId: anon_enc
      address:
      abi:
    - name: Zeto_NfAnon
      circuitId: nf_anon
      address:
      abi:
