contracts:
  factory:
    abiAndBytecode:
      path: ./abis/ZetoFactory.json
  # the Zeto factory is a CloneFactory, which needs implementation
  # contracts to be set
  implementations:
    # for the deposit transaction
    - name: Groth16Verifier_CheckHashesValue
      abiAndBytecode:
        path: ./abis/Groth16Verifier_CheckHashesValue.json
    # for the withdraw transaction
    - name: Groth16Verifier_CheckInputsOutputsValue
      abiAndBytecode:
        path: ./abis/Groth16Verifier_CheckInputsOutputsValue.json
    # for the withdraw transaction with batch inputs
    - name: Groth16Verifier_CheckInputsOutputsValueBatch
      abiAndBytecode:
        path: ./abis/Groth16Verifier_CheckInputsOutputsValueBatch.json
    # for the withdraw transaction with nullifiers
    - name: Groth16Verifier_CheckNullifierValue
      abiAndBytecode:
        path: ./abis/Groth16Verifier_CheckNullifierValue.json
    # for the withdraw transaction with batch inputs and nullifiers
    - name: Groth16Verifier_CheckNullifierValueBatch
      abiAndBytecode:
        path: ./abis/Groth16Verifier_CheckNullifierValueBatch.json
    # for the Zeto_Anon token
    - name: Groth16Verifier_Anon
      abiAndBytecode:
        path: ./abis/Groth16Verifier_Anon.json
    - name: Groth16Verifier_AnonBatch
      abiAndBytecode:
        path: ./abis/Groth16Verifier_AnonBatch.json
    - name: Zeto_Anon
      verifier: Groth16Verifier_Anon
      batchVerifier: Groth16Verifier_AnonBatch
      depositVerifier: Groth16Verifier_CheckHashesValue
      withdrawVerifier: Groth16Verifier_CheckInputsOutputsValue
      batchWithdrawVerifier: Groth16Verifier_CheckInputsOutputsValueBatch
      circuits:
        deposit: check_hashes_value
        withdraw: check_inputs_outputs_value
        withdrawBatch: check_inputs_outputs_value_batch
        transfer: anon
        transferBatch: anon_batch
        transferLocked: anon
        transferLockedBatch: anon_batch
      cloneable: true
      abiAndBytecode:
        path: ./abis/Zeto_Anon.json
    # for the Zeto_AnonEnc token
    # - name: Groth16Verifier_AnonEnc
    #   abiAndBytecode:
    #     path: ./abis/Groth16Verifier_AnonEnc.json
    # - name: Groth16Verifier_AnonEncBatch
    #   abiAndBytecode:
    #     path: ./abis/Groth16Verifier_AnonEncBatch.json
    # - name: Zeto_AnonEnc
    #   verifier: Groth16Verifier_AnonEnc
    #   batchVerifier: Groth16Verifier_AnonEncBatch
    #   depositVerifier: Groth16Verifier_CheckHashesValue
    #   withdrawVerifier: Groth16Verifier_CheckInputsOutputsValue
    #   batchWithdrawVerifier: Groth16Verifier_CheckInputsOutputsValueBatch
    #   lockVerifier: Groth16Verifier_CheckUtxosOwner
    #   batchLockVerifier: Groth16Verifier_CheckUtxosOwnerBatch
    #   circuitId: anon_enc
    #   cloneable: true
    #   abiAndBytecode:
    #     path: ./abis/Zeto_AnonEnc.json
    # for the Zeto_AnonNullifier token
    - name: PoseidonUnit2L
      abiAndBytecode:
        path: ./abis/Poseidon2.json
    - name: PoseidonUnit3L
      abiAndBytecode:
        path: ./abis/Poseidon3.json
    - name: SmtLib
      abiAndBytecode:
        path: ./abis/SmtLib.json
    - name: Groth16Verifier_AnonNullifierTransfer
      abiAndBytecode:
        path: ./abis/Groth16Verifier_AnonNullifierTransfer.json
    - name: Groth16Verifier_AnonNullifierTransferBatch
      abiAndBytecode:
        path: ./abis/Groth16Verifier_AnonNullifierTransferBatch.json
    - name: Groth16Verifier_AnonNullifierTransferLocked
      abiAndBytecode:
        path: ./abis/Groth16Verifier_AnonNullifierTransferLocked.json
    - name: Groth16Verifier_AnonNullifierTransferLockedBatch
      abiAndBytecode:
        path: ./abis/Groth16Verifier_AnonNullifierTransferLockedBatch.json
    - name: Zeto_AnonNullifier
      verifier: Groth16Verifier_AnonNullifierTransfer
      batchVerifier: Groth16Verifier_AnonNullifierTransferBatch
      depositVerifier: Groth16Verifier_CheckHashesValue
      withdrawVerifier: Groth16Verifier_CheckNullifierValue
      batchWithdrawVerifier: Groth16Verifier_CheckNullifierValueBatch
      lockVerifier: Groth16Verifier_AnonNullifierTransferLocked
      batchLockVerifier: Groth16Verifier_AnonNullifierTransferLockedBatch
      circuits:
        deposit: check_hashes_value
        withdraw: check_nullifiers_value
        withdrawBatch: check_nullifiers_value_batch
        transfer: anon_nullifier_transfer
        transferBatch: anon_nullifier_transfer_batch
        transferLocked: anon_nullifier_transferLocked
        transferLockedBatch: anon_nullifier_transferLocked_batch
      cloneable: true
      abiAndBytecode:
        path: ./abis/Zeto_AnonNullifier.json
