run:
  timeout: 5m
  allow-parallel-runners: true

issues:
  # don't skip warning about doc comments
  # don't exclude the default set of lint
  exclude-use-default: false
  # restore some of the defaults
  # (fill in the rest as needed)
  exclude-rules:
    - path: "/*"
      linters:
        - lll
    - path: "internal/*"
      linters:
        - dupl
    - path: ".*_test.go"
      linters:
        - errcheck
    - path: "contractpkg/*"
      linters:
        - errcheck
linters:
  disable-all: true
  enable:
    - dupl
    - errcheck
    - exportloopref
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - typecheck
    - unconvert
    - unparam
    - unused
