name: Operator Build

on:
  workflow_call:
 
jobs:
  operator-build:
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: paladin
      NAMESPACE: paladin

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install pre-requisites
        uses: ./.github/actions/setup

      - name: Install Kind
        uses: helm/kind-action@v1
        with:
          install_only: true # only install kind, the cluster creation is managed by the deploy step
          ignore_failed_clean: true

      - name: Download docker artifacts
        uses: actions/download-artifact@v4
        with:
          path: /tmp # download all docker images to /tmp
          pattern: paladin-*
          merge-multiple: true
      
      - name: Load image
        run: |
          docker load --input /tmp/paladin-operator-${{ github.sha }}.tar
          docker load --input /tmp/paladin-${{ github.sha }}.tar
          docker image ls -a  
      
      # The makefile uses kustomize
      - uses: imranismail/setup-kustomize@v2

      - name: Deploy Operator
        run: |
          ./gradlew deploy \
            -PclusterName=${{ env.CLUSTER_NAME }} \
            -Pnamespace=${{ env.NAMESPACE }} \
            -PbuildOperator=false \
            -PbuildPaladin=false \
            -PoperatorImageName=paladin.io/paladin-operator \
            -PoperatorImageTag=test \
            -PpaladinImageName=paladin.io/paladin \
            -PpaladinImageTag=test 

      - name: Uninstall Operator
        run: |
          ./gradlew clean \
            -PclusterName=${{ env.CLUSTER_NAME }} \
            -Pnamespace=${{ env.NAMESPACE }} \
            -PdeleteCluster=true