# This workflow tests the examples ensuring they are aligned with the latest SDK
name: Test Examples changes
permissions:
  contents: write
  packages: write
  id-token: write

on:
  push:
    branches:
      - main
    paths:
      - 'scripts/**'
      - 'example/**'
      - '.github/workflows/on-pr-push-examples.yaml'
  pull_request:
    paths:
      - 'scripts/**'
      - 'example/**'
      - '.github/workflows/on-pr-push-examples.yaml'

# Ensure this workflow only runs for the most recent commit of a pull-request
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test-examples:
    uses: ./.github/workflows/test-examples.yaml
    with:
      build_local_sdk: false # this workflow is meant to test the examples with the published SDK