# This workflow tests the examples ensuring they are aligned with the latest SDK
name: Test Tutorials changes
permissions:
  contents: write
  packages: write
  id-token: write

on:
  push:
    branches:
      - main
    paths:
      - 'scripts/**'
      - 'examples/**'
      - '.github/workflows/on-pr-push-examples.yaml'
      - '.github/workflows/test-tutorials.yaml'

  pull_request:
    paths:
      - 'scripts/**'
      - 'examples/**'
      - '.github/workflows/on-pr-push-examples.yaml'
      - '.github/workflows/test-tutorials.yaml'

# Ensure this workflow only runs for the most recent commit of a pull-request
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-tutorials:
    uses: ./.github/workflows/test-tutorials.yaml
    with:
      build_local_sdk: false # this workflow is meant to test the tutorials with the published SDK
      build_local_abi: false # this workflow is meant to test the tutorials with the published solidity contracts
      run_commands: start,verify # run the start and validate to ensure the tutorials are not broken
