name: Build (PR)
permissions:
  contents: write
  packages: write
  id-token: write

on:
  pull_request:

# Ensure this workflow only runs for the most recent commit of a pull-request
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  core-image-build:
    uses: ./.github/workflows/build-image.yaml
    with:
      dockerfile: ./Dockerfile
      registry: paladin.io
      image: paladin
      image_tag: ${{ github.sha }}
      push: false
      upload-artifact: true
      platforms: linux/amd64
      runs-on: ubuntu-latest

  operator-image-build:
    uses: ./.github/workflows/build-image.yaml
    with:
      dockerfile: ./operator/Dockerfile
      registry: paladin.io
      image: paladin-operator
      image_tag: ${{ github.sha }}
      push: false
      upload-artifact: true
      platforms: linux/amd64
      runs-on: ubuntu-latest

  chart-build:
    needs: [core-image-build, operator-image-build]
    uses: ./.github/workflows/build-chart.yaml
    with:
      paladin-image: paladin.io/paladin
      paladin-image-tag: ${{ github.sha }}
      operator-image: paladin.io/paladin-operator
      operator-image-tag: ${{ github.sha }}
