name: Paladin Operator Build

on:
  push:
    branches: [main]
    paths:
      - 'operator/**'
  pull_request:
    paths:
      - 'operator/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
 
      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true
      
      # Linter
      - name: Go Lint
        working-directory: ./operator
        run: make lint

      # Test
      - name: Test
        working-directory: ./operator
        run: make test

      # Test e2e
      - name: Test e2e
        working-directory: ./operator
        run: make test-e2e
          
      - name: Kubernetes Kind Cluster
        uses: helm/kind-action@v1

      - name: Install Operator
        working-directory: ./operator
        run: make helm-install

      - name: Uninstall Operator
        working-directory: ./operator
        run: make helm-uninstall
       