name: PR
permissions: read-all
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths-ignore:
      - '**.sh'
      - 'docs/*'
      - 'build/*'
      - '.github/*'
      # - '**.md' // Uncomment this line to ignore all markdown files

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-and-build:
    permissions:
      actions: read
      checks: read
      deployments: read
      id-token: write
      issues: read
      discussions: read
      packages: read
      pages: read
      pull-requests: write
      repository-projects: read
      security-events: read
      statuses: read
      attestations: read
      contents: write
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      artifacts_path: buils/libs

  build-image:
    needs: test-and-build
    permissions:
      actions: read
      checks: read
      contents: write
      deployments: read
      discussions: read
      id-token: write
      issues: read
      packages: write
      pages: read
      pull-requests: read
      repository-projects: read
      security-events: read
      statuses: read
      attestations: read
    uses: ./.github/workflows/image-build.yaml
    with:
      artifacts_path: buils/libs
      image_name: paladin
      image_tag: pr-test
      build_platform: linux/amd64

    secrets: inherit
