name: Upload Solidity Artifacts
on:
  workflow_call:
    inputs:
      ref:
        description: 'Commit ref for checkout'
        required: false
        type: string
        default: ''
      tag:
        description: 'The tag of the release'
        required: true
        type: string
       
  workflow_dispatch:
    inputs:
      ref:
        description: 'Commit ref for checkout'
        required: false
        type: string
        default: ''
      tag:
        description: 'The tag of the release'
        required: true
        type: string

  pull_request:
    paths:
      - '.github/workflows/release-solidity-contracts.yaml'
      - 'solidity/**'
      - 'domains/zeto/build.gradle'

  push:
    paths:
      - '.github/workflows/release-solidity-contracts.yaml'
      - 'solidity/**'
      - 'domains/zeto/build.gradle'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  
  upload:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
        ref: ${{ inputs.ref != '' && inputs.ref || github.ref }}

    - name: Install pre-requisites
      uses: ./.github/actions/setup

    - name: Build Solidity Contracts
      working-directory: solidity
      run: ../gradlew build 

    - name: Copy Solidity artifacts to paladin-contracts directory
      shell: bash
      run: |
        mkdir -p paladin-contracts
        find solidity/artifacts/contracts -type f -name "*.json" ! -name "*.dbg.json" -exec cp {} paladin-contracts/ \;

    - name: Download Zeto contracts
      working-directory: domains/zeto
      shell: bash
      run: |
        mkdir -p tools/contracts

        # Download zeto contracts (downloads to domains/zeto/tools/zeto-contracts-v0.2.0.tar.gz)
        ../../gradlew downloadZetoCompiledContracts

        # Unzip zeto contracts
        # TODO: remove hardcoded version from name (should be available after zeto release v0.3.0)
        # issue: https://github.com/hyperledger-labs/zeto/issues/158
        tar -xzf tools/zeto-contracts-v0.2.0.tar.gz -C tools/contracts

    - name: Copy Zeto Solidity artifacts to zeto-contracts directory
      shell: bash
      run: |
        mkdir -p zeto-contracts
        find domains/zeto/tools/contracts -type f -name "*.json" ! -name "*.dbg.json" -exec cp {} zeto-contracts/ \;

    - name: Archive ABI directory
      run: |
        mkdir -p  contracts
        tar -czvf contracts/abis.tar.gz -C paladin-contracts .
        tar -czvf contracts/zeto-abis.tar.gz -C zeto-contracts .

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      id: upload-artifacts
      with:
        name: contracts
        path: contracts/

    - name: Print upload-artifacts output
      shell: bash
      run: |
        echo "upload-artifacts URL: ${{ steps.upload-artifacts.outputs.artifact-url }}"