name: TypeScript SDK Release
on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        description: 'NPM token'
        required: true
    inputs:
      sdk_version:
        description: 'The version to publish (e.g. 1.0.0)'
        required: true
        type: string
      sdk_tag:
        description: 'The tag to publish (e.g. latest, rc, stable)'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      sdk_version:
        description: 'The version to publish (e.g. 1.0.0)'
        required: true
        type: string
      sdk_tag:
        description: 'The tag to publish (e.g. latest, rc, stable)'
        required: true
        type: string

jobs:
  test:
    # make sure the released candidate SDK is not breaking the tutorials
    uses: ./.github/workflows/test-tutorials.yaml
    with:
      build_local_abi: false # we are using the published abi
      build_local_sdk: true # we are using the local sdk
  publish:
    needs: test
    permissions:
      contents: read
      id-token: write
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pre-requisites
        uses: ./.github/actions/setup

      # Override package.json version
      - name: Override SDK version
        uses: ./.github/actions/update-json
        with:
          file: 'sdk/typescript/package.json'
          key: 'version'
          value: ${{ inputs.sdk_version }}

      - name: Publish to npm
        continue-on-error: true # this can fail if the version is already published
        working-directory: sdk/typescript
        shell: bash
        run: |
          set -e
          ../../gradlew build
          npm publish --provenance --access public --tag ${{ inputs.sdk_tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          