name: Trigger image build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - '**.java'
      - '**/build.gradle'
      - '**/Dockerfile'
      - '.github/workflows/build-image*.yaml'

jobs:
  call-image-build-workflow:
    uses: ./.github/workflows/build-images.yaml
    with:
      registry: ghcr.io
      repository: ${{ github.repository_owner }}
      image_tag: ${{ github.ref_name }}
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
